.PHONY: clean All

All:
	@echo "----------Building project:[ lab10A - Debug ]----------"
	@cd "lab10A" && "$(MAKE)" -f  "lab10A.mk"
clean:
	@echo "----------Cleaning project:[ lab10A - Debug ]----------"
	@cd "lab10A" && "$(MAKE)" -f  "lab10A.mk" clean
